from snakemake.utils import min_version
import sys


min_version("8.0.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


##### Target rules #####


include: "rules/init.smk"
include: "rules/downsample.smk"
include: "rules/bakta.smk"
include: "rules/region_decompression.smk"
include: "rules/genome_decompression.smk"
include: "rules/tree.smk"
include: "rules/align.smk"



## WILDCARDS CONSTRAINS
wildcard_constraints:
    sample=r"[a-zA-Z0-9_-]+",
    batch=r"[a-zA-Z0-9_-]+",

rule all:
    input:
        expand(
            fn_downsampled_df("{batch}", "{genebatch}", "{passinggene}"),
            zip,
            batch=get_passinggenes_batches(),
            genebatch=get_passinggenes_genebatches(),
            passinggene=get_passinggenes(),
        ),
        expand(
            fn_downsample_nwk("{batch}", "{genebatch}", "{passinggene}"),
            zip,
            batch=get_passinggenes_batches(),
            genebatch=get_passinggenes_genebatches(),
            passinggene=get_passinggenes(),
        ),
        #expand(
            #fn_decompregion_agg("{batch}", "{genebatch}", "{passinggene}"),
            #zip,
            #batch=get_passinggenes_batches(),
            #genebatch=get_passinggenes_genebatches(),
            #passinggene=get_passinggenes(),
        #),
        expand(
            fn_itoltree("{batch}", "{genebatch}", "{passinggene}"),
            zip,
            batch=get_passinggenes_batches(),
            genebatch=get_passinggenes_genebatches(),
            passinggene=get_passinggenes(),
        ),
        expand(
            fn_mincuts("{batch}", "{genebatch}", "{passinggene}"),
            zip,
            batch=get_passinggenes_batches(),
            genebatch=get_passinggenes_genebatches(),
            passinggene=get_passinggenes(),
        ),
        expand(
            fn_bakta_annot_done("{batch}", "{genebatch}", "{passinggene}"),
            zip,
            batch=get_passinggenes_batches(),
            genebatch=get_passinggenes_genebatches(),
            passinggene=get_passinggenes(),
        )
        expand(
            fn_blast_done("{batch}", "{genebatch}", "{passinggene}"),
            zip,
            batch=get_passinggenes_batches(),
            genebatch=get_passinggenes_genebatches(),
            passinggene=get_passinggenes(),
        )
