from snakemake.utils import min_version
import sys


min_version("8.0.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


##### Target rules #####
include: "rules/init.smk"
include: "rules/downsample.smk"
include: "rules/bakta.smk"
include: "rules/region_decompression.smk"
include: "rules/genome_decompression.smk"
include: "rules/tree.smk"
include: "rules/align.smk"
include: "rules/deletion_or_insertion_mgerecords.smk"
#include: "rules/deletion_or_insertion.smk"


## WILDCARDS CONSTRAINS
wildcard_constraints:
    sample=r"[a-zA-Z0-9_-]+",
    batch=r"[a-zA-Z0-9_-]+",


localrules:
    downsample_annotdf,
    downsample_df,
    build_tinyfilelist,
    extract_internal_kmers,
    find_passing_genes,
    select_buckets,
    tinydownsample_df,
    analyze_bwafastmap

rule all:
    input:
        get_filtered_gene_outputs,
        #fn_passinggenes_agg(),
        #expand(
            #fn_downsampled_df("{batch}", "{genebatch}", "{passinggene}"),
            #zip,
            #batch=get_passinggenes_batches(),
            #genebatch=get_passinggenes_genebatches(),
            #passinggene=get_passinggenes(),
        #),
        #expand(
            #fn_downsample_nwk("{batch}", "{genebatch}", "{passinggene}"),
            #zip,
            #batch=get_passinggenes_batches(),
            #genebatch=get_passinggenes_genebatches(),
            #passinggene=get_passinggenes(),
        #),
        #expand(
            #fn_itoltree("{batch}", "{genebatch}", "{passinggene}"),
            #zip,
            #batch=get_passinggenes_batches(),
            #genebatch=get_passinggenes_genebatches(),
            #passinggene=get_passinggenes(),
        #),
        #expand(
            #fn_mincuts("{batch}", "{genebatch}", "{passinggene}"),
            #zip,
            #batch=get_passinggenes_batches(),
            #genebatch=get_passinggenes_genebatches(),
            #passinggene=get_passinggenes(),
        #),
        #expand(
            #fn_passinggenes_agg("{batch}", "{genebatch}"),
            #zip,
            #batch=get_passinggenes_batches(),
            #genebatch=get_passinggenes_genebatches(),
        #),
        #expand(
        #fn_blast_done("{batch}", "{genebatch}", "{passinggene}"),
        #zip,
        #batch=get_passinggenes_batches(),
        #genebatch=get_passinggenes_genebatches(),
        #passinggene=get_passinggenes(),
        #),
        #expand(
        #fn_decompregion_agg("{batch}", "{genebatch}", "{passinggene}"),
        #zip,
        #batch=get_passinggenes_batches(),
        #genebatch=get_passinggenes_genebatches(),
        #passinggene=get_passinggenes(),
        #),
        #expand(
        #fn_bakta_annot_done("{batch}", "{genebatch}", "{passinggene}"),
        #zip,
        #batch=get_passinggenes_batches(),
        #genebatch=get_passinggenes_genebatches(),
        #passinggene=get_passinggenes(),
        #),
        #rules.fanout_analysis.output,
        #expand(
        #fn_fastmapraw_agg("{batch}", "{genebatch}", "{passinggene}"),
        #zip,
        #batch=get_passinggenes_batches(),
        #genebatch=get_passinggenes_genebatches(),
        #passinggene=get_passinggenes(),
        #),
