from snakemake.utils import min_version
import sys


min_version("6.2.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


##### Target rules #####


include: "rules/init.smk"
include: "rules/bwa.smk"


## WILDCARDS CONSTRAINS
wildcard_constraints:
    sample=r"[a-zA-Z0-9_-]+",
    batch=r"[a-zA-Z0-9_-]+",


rule all:
    input:
        #expand(fn_prefsuffkmer(_gene="{gene}", _sample="{sample}"), _gene=fn_genes(), _sample=fn_samples())
        expand(fn_idxpersample(_sample="{sample}"), _sample=get_samples())


##### Modules #####
