from snakemake.utils import min_version
import sys


min_version("8.0.0")

shell.prefix("set -euo pipefail")


report: "report/workflow.rst"


##### Target rules #####


include: "rules/init.smk"
include: "rules/bwa.smk"
include: "rules/kmercreation.smk"
include: "rules/fastmap_processing.smk"
include: "rules/clusterdists.smk"
include: "rules/genome_decompression.smk"


## WILDCARDS CONSTRAINS
wildcard_constraints:
    sample=r"[a-zA-Z0-9_-]+",
    batch=r"[a-zA-Z0-9_-]+",


rule all:
    input:
        expand(
            f"{dir_output()}" + "/passing_genes-{batch}-{genebatch}.txt",
            batch=get_genome_batches(),
            genebatch=get_gene_batches(),
        ),
