#!/usr/bin/env python3

import sys
import os
import argparse
from loguru import logger
import pandas as pd


# Function to write distances for each gene to a file
def write_distances(group, file, k, g):
    prefix_df = group[group["KmerType"].str.contains("prefix")]
    suffix_df = group[group["KmerType"].str.contains("suffix")]

    for _, prefix_row in prefix_df.iterrows():
        for _, suffix_row in suffix_df.iterrows():
            prefix_loc = prefix_row['Location']
            suffix_loc = suffix_row['Location']
            if prefix_row["Contig"] == suffix_row["Contig"] and prefix_row[
                    'Contig'] != "Null":
                distance = abs(
                    int(suffix_row["Location"]) -
                    int(prefix_row["Location"])) + k + 2 * g
                # print(prefix_row['GeneID'])
                # print(prefix_row['GeneID'].split('-')[-1])
                length = int(prefix_row['GeneID'].split("-")[-1][3:])
                difference = distance - length
            else:
                if prefix_row['Contig'] != suffix_row['Contig']:
                    distance = "ContigsDifferent"
                if prefix_row['Contig'] == "Null" or suffix_row[
                        'Contig'] == "Null":
                    distance = "KmerNotFound"
                difference = "NaN"
            file.write(
                f"{prefix_row['GeneID']}\t{prefix_row['kmerID']}\t{suffix_row['kmerID']}\t{prefix_row['Contig']}\t{distance}\t{difference}\t{prefix_loc}\t{suffix_loc}\n"
            )


def main():
    parser = argparse.ArgumentParser(
        description=
        "Extract k-mer sequences from a genome based on a provided locus tag and TSV file."
    )

    parser.add_argument(
        "-i",
        "--input",
        type=str,
        required=True,
        help="Input processed bwa fastmap output",
        metavar="FILE",
    )

    parser.add_argument(
        "-o",
        "--output",
        type=str,
        required=True,
        help="Output distance dataframe for mappings",
        metavar="FILE",
    )

    parser.add_argument(
        "-k",
        "--kmer-length",
        type=int,
        required=True,
        help="Kmer Length",
    )

    parser.add_argument(
        "-g",
        "--gap-distance",
        type=int,
        required=True,
        help="Gap distance",
    )

    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help=
        "Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    # Parse the arguments
    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    df = pd.read_csv(args.input, sep="\t")
    df[["GeneID", "KmerType"]] = df["kmerID"].str.rsplit("_", n=3,
                                                         expand=True)[[0, 1]]

    with open(args.output, "w") as file:
        file.write(
            "GeneID\tPrefix\tSuffix\tContig\tDistance\tDifference\tPrefixLocation\tSuffixLocation\n"
        )  # Write header
        # Iterate over each gene group and write distances
        for name, group in df.groupby("GeneID"):
            logger.info(f"Writing information for {name}")
            write_distances(group, file, args.kmer_length, args.gap_distance)


if __name__ == "__main__":
    main()
