#!/usr/bin/env python

import scipy
import sys
import pandas as pd
import numpy as np
import re
import glob
import os
import argparse
from loguru import logger
from sklearn.cluster import DBSCAN
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.collections import PathCollection
import concurrent.futures


def read_and_filter_csv(file):
    df = pd.read_csv(file)
    # Filter out columns that are entirely NA
    filtered_df = df.dropna(axis=1, how='all')
    return filtered_df


# Function to read all CSV files and concatenate them into a single DataFrame
def aggregate_results(folder_path):
    all_files = glob.glob(folder_path + "/*.csv")
    df = pd.DataFrame()
    for f in all_files:
        indiv_data = read_and_filter_csv(f)
        basename_f = os.path.basename(f)
        bucket_f = re.sub(r"(_\d+)-filterdists\.csv", "", basename_f)
        indiv_data['Bucket'] = bucket_f
        df = pd.concat((df, indiv_data), ignore_index=True)
    return df

def assign_cluster_colors(labels):
    # Sort unique labels, ensuring -1 is last
    unique_labels = sorted(set(labels), key=lambda x: (x == -1, x))
    logger.debug(f"Sorted Labels: {unique_labels}")

    # Get colors from the seaborn muted palette
    n_colors = len(unique_labels)
    logger.debug(f"Number of colors: {n_colors}")

    # Generate a color palette with enough distinct colors
    base_palette = sns.color_palette("muted", as_cmap=False).as_hex()
    if n_colors > len(base_palette):
        logger.warning(f"{n_colors} is more than in the seaborn palette. Adding new colors with different brightness.")
        extended_palette = base_palette + sns.color_palette("muted", n_colors-len(base_palette), desat=0.6).as_hex()
    else:
        extended_palette = base_palette

    colors = extended_palette[:n_colors]
    logger.debug(f"Available colors: {colors}")

    # Initialize label_color_map with regular clusters
    label_color_map = {label: colors[i] for i, label in enumerate(unique_labels) if label != -1}

    # If -1 is in labels, assign it the last color from the palette
    if -1 in unique_labels:
        label_color_map[-1] = colors[-1]  # Assigning the last color in the palette to -1

    return label_color_map

# Function to process a single gene
def process_gene(gene, gene_data, epsilon, min_samples, output_dir):
    logger.debug(f"Processing gene: {gene}")
    gene_name = gene
    if '/' in gene_name:
        logger.warning(f"{gene_name} contains '/', replacing '/' with ':'")
        gene_name = gene_name.replace('/',':')
        logger.warning(f"{gene_name} replaces {gene}")
    if '|' in gene_name:
        logger.warning(f"{gene_name} contains '|', replacing '|' with ':'")
        gene_name = gene_name.replace('|',':')
        logger.warning(f"{gene_name} replaces {gene}")
    if '(' in gene_name:
        logger.warning(f"{gene_name} contains '(', deleting '('")
        gene_name = gene_name.replace('(','')
        logger.warning(f"{gene_name} replaces {gene}")
    if ')' in gene_name:
        logger.warning(f"{gene_name} contains ')', deleting ')'")
        gene_name = gene_name.replace(')','')
        logger.warning(f"{gene_name} replaces {gene}")
    if "'" in gene_name:
        logger.warning(f"{gene_name} contains \"'\", deleting \"'\"")
        gene_name = gene_name.replace("'","")
        logger.warning(f"{gene_name} replaces {gene}")

    # Count the occurrences of each unique value for sample_weight
    value_counts = gene_data["Difference"].value_counts()

    # Remove exact duplicates
    gene_data_unique = gene_data.drop_duplicates(subset=["Difference"])

    # Reshape for DBSCAN
    differences = gene_data_unique["Difference"].values.reshape(-1, 1)

    create_violin_plot(
        gene_data, gene_name,
        os.path.join(output_dir, "all_differencedist_plots",
                     f"{gene_name}_dist.png"))

    logger.debug(f"Clustering differences")
    dbscan = DBSCAN(eps=epsilon, min_samples=min_samples, n_jobs=-1)

    logger.debug(f"Fitting labels")

    # Use sample_weight in DBSCAN
    sample_weight = value_counts.loc[gene_data_unique["Difference"]].values
    labels = dbscan.fit_predict(differences, sample_weight=sample_weight)

    logger.debug(f"Checking gene labels")

    # Check if the gene meets the criteria
    label_set = set(labels)
    if (-1 in label_set and len(label_set) <= 2) or len(label_set) < 2:
        return gene, None, False, None

    logger.info(
        f"{gene} passed filter with the following clusters: {label_set}")

    # Compute mean distance for each cluster except noise (-1)
    cluster_means = {}
    for label in label_set:
        if label != -1:
            cluster_members = differences[labels == label]
            mean_distance = np.mean(cluster_members)
            cluster_means[label] = mean_distance

    # Sort clusters based on their mean distance and assign new labels
    sorted_clusters = sorted(cluster_means, key=cluster_means.get)
    cluster_mapping = {old_label: new_label for new_label, old_label in enumerate(sorted_clusters)}

    # Replace old labels with new labels
    new_labels = np.array([cluster_mapping[label] if label != -1 else -1 for label in labels])

    # Create a mapping from unique values to labels
    mapping = dict(zip(gene_data_unique["Difference"], new_labels))

    # gene_df = df[df["GeneID"] == gene].copy()
    gene_df = gene_data.copy()
    gene_df["Cluster"] = gene_df['Difference'].map(mapping)
    outdir = os.path.join(output_dir, "passing_genes", gene_name)
    os.makedirs(outdir, exist_ok=True)

    # Plotting and saving
    create_violin_plot_ofclusters(
        gene_df, gene_name,
        os.path.join(outdir, f"{gene_name}_coloreddist.png"))
    create_kde_plot(
        gene_df, gene_name,
        os.path.join(outdir, f"{gene_name}_kde.png")
    )
    gene_df.to_csv(os.path.join(outdir, f"{gene_name}_clusters.csv"),
                   index=False)

    return gene, mapping, True, gene_name


# Function to perform clustering and save results
def cluster_gene_differences_threaded(df, epsilon, min_samples, output_dir):
    grouped_data = df.groupby('GeneID')

    num_failing_genes = 0
    num_passing_genes = 0
    with concurrent.futures.ProcessPoolExecutor() as executor:
        futures = {}
        for gene, gene_data in grouped_data:
            futures[executor.submit(process_gene, gene, gene_data, epsilon,
                                    min_samples, output_dir)] = gene

        for future in concurrent.futures.as_completed(futures):
            gene, mapping, is_worthy, gene_name = future.result()

            if is_worthy:
                num_passing_genes += 1
            else:
                num_failing_genes += 1
                # gene_df = df[df["GeneID"] == gene].copy()
                # gene_df["Cluster"] = gene_df['Difference'].map(mapping)
                # outdir = os.path.join(output_dir, "passing_genes", gene_name)
                # os.makedirs(outdir, exist_ok=True)

                # create_violin_plot_ofclusters(
                    # gene_df, gene_name,
                    # os.path.join(outdir, f"{gene_name}_coloreddist.png"))
                # create_kde_plot(
                    # gene_df, gene_name,
                    # os.path.join(outdir, f"{gene_name}_kde.png")
                # )
                # gene_df.to_csv(os.path.join(outdir, f"{gene_name}_clusters.csv"),
                               # index=False)
    return num_passing_genes, num_failing_genes


# Function to plot difference distribution for a gene
def create_violin_plot(gene_df, gene_id, output_file):
    plt.figure(figsize=(10, 6))

    ax = sns.stripplot(
        x='Difference',
        data=gene_df,
        jitter=0.35,
        color='grey',
        orient="h",
        alpha=0.8
    )

    sns.violinplot(
        x='Difference',
        data=gene_df,
        fill=False,
        inner=None,
        cut=0,
        color='black',
        split=False,
        bw_method=0.02,
    )
    plt.ylabel("Density")
    plt.xlabel("Distance Difference compared to gene (bp)")
    plt.title(f"Gene: {gene_id}")
    sns.despine(left=True)
    plt.savefig(output_file, dpi=200)
    plt.close()

def fulldist_colorclusters(gene_df, gene_id, output_file):
    plt.figure(figsize=(10, 6))

    ax = sns.violinplot(x="Difference",
                        data=gene_df,
                        fill=False,
                        color="black",
                        bw_method=0.02,
                        inner=None)
    for artist in ax.lines:
        artist.set_zorder(10)
    for artist in ax.findobj(PathCollection):
        artist.set_zorder(11)

    palette = assign_cluster_colors(gene_df['Cluster'])

    sns.stripplot(x="Difference",
                  hue='Cluster',
                  data=gene_df,
                  jitter=0.35,
                  ax=ax,
                  orient="h",
                  alpha=0.8,
                  zorder=1)
    plt.title(f"Gene: {gene_id}")
    plt.xlabel("Difference (bp)")
    sns.despine()
    plt.savefig(output_file, dpi=200, bbox_inches='tight')
    plt.close()


# Function to create violin plots for each gene
def create_violin_plot_ofclusters(gene_df, gene_id, output_file):
    plt.figure(figsize=(10, 6))

    ax = sns.violinplot(
        x='Difference',
        data=gene_df,
        fill=False,
        inner=None,
        cut=0,
        color='black',
        split=False,
        bw_method=0.02,
    )

    palette = assign_cluster_colors(gene_df['Cluster'])

    sns.stripplot(
        x='Difference',
        hue='Cluster',
        data=gene_df,
        jitter=0.35,
        orient="h",
        ax=ax,
        palette=palette
    )

    plt.ylabel("Density")
    plt.xlabel("Distance Difference compared to gene (bp)")
    plt.title(f"Gene: {gene_id}")
    sns.despine(left=True)
    plt.savefig(output_file, dpi=200, bbox_inches='tight')
    plt.close()

def create_kde_plot(gene_df, gene_id, output_file):
    ax = sns.kdeplot(data=gene_df, x="Difference", color='black')
    sns.despine()
    plt.ylabel("Density")
    plt.xlabel("Distance Difference compared to gene (bp)")
    plt.title(f"Gene: {gene_id}")
    plt.savefig(output_file, dpi=200, bbox_inches='tight')

def main():
    parser = argparse.ArgumentParser(description="Gene clustering script.")
    parser.add_argument(
        "-i",
        "--input_dir",
        type=str,
        required=True,
        help="Directory containing input CSV files.",
    )
    parser.add_argument(
        "-o",
        "--output_dir",
        type=str,
        required=True,
        help="Directory to store output files.",
    )
    parser.add_argument("--epsilon",
                        type=float,
                        default=800,
                        help="Epsilon value for DBSCAN.")
    parser.add_argument("--min_samples",
                        type=int,
                        default=20,
                        help="Minimum samples value for DBSCAN.")
    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help=
        "Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    os.makedirs(os.path.join(args.output_dir, "all_differencedist_plots"),
                exist_ok=True)
    passinggenesdir = os.path.join(args.output_dir, "passing_genes")
    os.makedirs(passinggenesdir, exist_ok=True)
    df = aggregate_results(args.input_dir)
    logger.info("Read all input files.")
    (num_passing_genes, num_failing_genes) = cluster_gene_differences_threaded(
        df, args.epsilon, args.min_samples, args.output_dir)
    logger.info(f"Passing genes: {num_passing_genes} ({(num_passing_genes/(num_passing_genes+num_failing_genes))*100}%)\nFailing genes: {num_failing_genes} ({(num_failing_genes/(num_passing_genes+num_failing_genes))*100}%)")
    logger.success("Complete.")


if __name__ == "__main__":
    main()
