#!/usr/bin/env python3

import sys
import os
import argparse
import pandas as pd
import seaborn as sns
from loguru import logger


# Function to extract and normalize k-mer position
def normalize_kmer_position(kmer_id):
    # Extract the position and total (e.g., '18of20')
    pos, total = kmer_id.split('_')[-1].split('of')
    pos, total = int(pos), int(total)
    # Normalize position
    return pos / total


def readin_results(input_file):
    df = pd.read_csv(input_file, sep='\t')
    df['geneID'] = df['kmerID'].str.split('-', expand=True)[0]
    df['NormalizedPosition'] = df['kmerID'].apply(normalize_kmer_position)
    palette = sns.color_palette("vlag",
                                n_colors=len(
                                    df['NormalizedPosition'].unique()))
    color_map = {
        pos: palette[i]
        for i, pos in enumerate(sorted(df['NormalizedPosition'].unique()))
    }
    df['Color'] = df['NormalizedPosition'].map(color_map)
    return df


# def group_results(df):


def main():
    parser = argparse.ArgumentParser(
        description="Read in raw fastmap output and parse it into a tsv file")

    parser.add_argument(
        "-i",
        "--input",
        type=str,
        required=True,
        help="Input bwa fastmap output",
        metavar="FILE",
    )

    parser.add_argument(
        "-o",
        "--output",
        type=str,
        required=True,
        help="Output analysis for bwa fastmap",
        metavar="FILE",
    )

    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help=
        "Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    # Parse the arguments
    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    df = readin_results(args.input)
    print(df)


if __name__ == "__main__":
    main()
