#!/usr/bin/env python3

import sys
from Bio import SeqIO
import argparse
from loguru import logger
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq


def process_fasta(input_fasta, k, g, n, output_fasta):
    output_records = []

    # Parse the input FASTA file
    logger.info("Parsing input fasta...")
    logger.info(
        f"Generating {n} {k}-mers with a gap distance of {g} for each record..."
    )
    for record in SeqIO.parse(input_fasta, "fasta"):
        logger.debug(f"Creating {n} k-mers for {record.id}")
        sequence = record.seq
        sequence_length = len(sequence)
        available_length = sequence_length - 2 * g

        if n > 1 and available_length > k:
            spacing = (available_length - k) // (n - 1)
        else:
            spacing = 0
        logger.debug(f"Spacing is calculated to be {spacing}")

        for i in range(n):
            logger.debug(f"Computing k-mer {i+1} of {n}")
            start = g + i * spacing
            end = start + k
            if end <= sequence_length - g:
                kmer = sequence[start:end]
                record = SeqRecord(
                    kmer,
                    id=f"{record.id}-len{sequence_length}_k{k}_{i+1}of{n}",
                    description="")
                output_records.append(record)
            else:
                logger.warning(
                    "No k-mer written! {record.id} is too short for specified k/n/g!"
                )
    logger.info(f"Created all pref/suff records. Writing to {output_fasta}")
    SeqIO.write(output_records, output_fasta, "fasta")


def main():
    parser = argparse.ArgumentParser(
        description=
        "Extract k-mer sequences from a genome based on a provided locus tag and TSV file."
    )

    parser.add_argument(
        "-i",
        "--input",
        type=str,
        required=True,
        help="Input fasta file, where each line is a gene",
        metavar="FILE",
    )

    parser.add_argument(
        "-o",
        "--output",
        type=str,
        required=True,
        help="Output fasta file path",
        metavar="FILE",
    )

    parser.add_argument(
        "-k",
        "--kmer-length",
        type=int,
        default=17,
        help="Length of k-mer to use for the matching. Default is 17",
    )

    parser.add_argument(
        "-g",
        "--gap-distance",
        type=int,
        default=4,
        help="Gap distance to use. Default is 4.",
    )
    parser.add_argument(
        "-n",
        "--number-kmers",
        type=int,
        default=10,
        help="Max number of k-mers to generate. Default is 10.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help=
        "Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    # Parse the arguments
    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    process_fasta(args.input, args.kmer_length, args.gap_distance,
                  args.number_kmers, args.output)


if __name__ == "__main__":
    main()
