#!/usr/bin/env python3

import sys
from Bio import SeqIO
import argparse
from loguru import logger
from Bio.SeqRecord import SeqRecord
from Bio.Seq import Seq


def process_fasta(input_fasta, k, n, output_fasta):
    output_records = []

    # Parse the input FASTA file
    logger.info("Parsing input fasta...")
    for record in SeqIO.parse(input_fasta, "fasta"):
        seq = record.seq

        # Check if sequence is long enough for the operation
        if len(seq) >= k + n:
            logger.debug(f"Creating prefix kmer for {record.id}")
            # Create the prefix k-mer after the gap distance n
            prefix_kmer = seq[n:n + k]
            prefix_record = SeqRecord(
                prefix_kmer,
                id=f"{record.id}-len{len(seq)}_prefix_k{k}_n{n}",
                description="")
            output_records.append(prefix_record)

            logger.debug(f"Creating suffix kmer for {record.id}")
            # Create the suffix k-mer before the gap distance n
            suffix_kmer = seq[-(n + k):-n]
            suffix_record = SeqRecord(
                suffix_kmer,
                id=f"{record.id}-len{len(seq)}_suffix_k{k}_n{n}",
                description="")
            output_records.append(suffix_record)
        else:
            logger.warning(
                f"{record.id} is too short for specified k/gap! Skipping...")

    # Convert the output records to a FASTA format string
    logger.info(f"Created all pref/suff records. Writing to {output_fasta}")
    # output_fasta = io.StringIO()
    SeqIO.write(output_records, output_fasta, "fasta")


def main():
    parser = argparse.ArgumentParser(
        description=
        "Extract k-mer sequences from a genome based on a provided locus tag and TSV file."
    )

    parser.add_argument(
        "-i",
        "--input",
        type=str,
        required=True,
        help="Input fasta file, where each line is a gene",
        metavar="FILE",
    )

    parser.add_argument(
        "-o",
        "--output",
        type=str,
        required=True,
        help="Output fasta file path",
        metavar="FILE",
    )

    parser.add_argument(
        "-k",
        "--kmer-length",
        type=int,
        default=17,
        help="Length of k-mer to use for the matching. Default is 17",
    )

    parser.add_argument(
        "-g",
        "--gap-distance",
        type=int,
        default=4,
        help="Gap distance to use. Default is 4.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help=
        "Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    # Parse the arguments
    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    process_fasta(args.input, args.kmer_length, args.gap_distance, args.output)


if __name__ == "__main__":
    main()
