#!/usr/bin/env python3

import sys
import os
import argparse
from loguru import logger


def parse_fastmap_output(file_path):
    parsed_kmers = 0
    parsed_data = []
    with open(file_path, "r") as file:
        seq_id = None
        for line in file:
            if line.startswith("SQ"):
                _, seq_id, _ = line.split(maxsplit=2)
                logger.debug(f"Parsing results for {seq_id}")
                parsed_kmers += 1
                wrote = False
            elif line.startswith("EM") and seq_id:
                logger.debug(f"Mappings found for {seq_id}")
                parts = line.split()
                num_mappings = int(parts[3])
                mappings = parts[4 : 4 + num_mappings]
                logger.debug(f"{num_mappings} mappings found for {seq_id}")
                for mapping in mappings:
                    contigid, location = mapping.split(":")
                    parsed_data.append([seq_id, contigid, location])
                wrote = True
            else:
                if wrote == False:
                    parsed_data.append([seq_id, "Null", "Null"])
                seq_id = None
            if parsed_kmers % 2000000 == 0:
                logger.info(f"Parsed {int(parsed_kmers/2)} prefix/suffix kmers!")
    return parsed_data


def write_to_tsv(data, output):
    with open(output, "w") as o:
        o.write("kmerID\tContig\tLocation\n")
        for lines in data:
            o.write(f"{lines[0]}\t{lines[1]}\t{lines[2]}\n")
    logger.info(f"Wrote output to {output}")


def main():
    parser = argparse.ArgumentParser(
        description="Extract k-mer sequences from a genome based on a provided locus tag and TSV file."
    )

    parser.add_argument(
        "-i",
        "--input",
        type=str,
        required=True,
        help="Input bwa fastmap output",
        metavar="FILE",
    )

    parser.add_argument(
        "-o",
        "--output",
        type=str,
        required=True,
        help="Output analysis for bwa fastmap",
        metavar="FILE",
    )

    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help="Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    # Parse the arguments
    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    data = parse_fastmap_output(args.input)
    logger.info(f"Writing {len(data)} fastmapped locations to {args.output}")
    write_to_tsv(data, args.output)


if __name__ == "__main__":
    main()
