#!/usr/bin/env python3

import sys
import os
import argparse
from loguru import logger
import gzip
from pathlib import Path


def parse_fastmap_output(file_path):
    parsed_kmers = 0
    parsed_data = []
    with gzip.open(file_path, "rt") as file:
        genome_id = None
        seq_id = None
        for line in file:
            if line.startswith("SQ"):
                _, seq_id, _ = line.split(maxsplit=2)
                logger.debug(f"Parsing results for {seq_id}")
                parsed_kmers += 1
                wrote = False
            elif line.startswith("EM") and seq_id:
                logger.debug(f"Mappings found for {seq_id}")
                parts = line.split()
                num_mappings = int(parts[3])
                mappings = parts[4:4 + num_mappings]
                logger.debug(f"{num_mappings} mappings found for {seq_id}")
                for mapping in mappings:
                    if mapping == "*":
                        logger.warning(
                            f"Too many hits for {seq_id} - BWTSA failed. Skipping."
                        )
                        break
                    contigid, location = mapping.split(":")
                    genome_id = contigid.split('.')[0]
                    parsed_data.append([genome_id, seq_id, contigid, location])
                wrote = True
            else:
                if wrote == False:
                    parsed_data.append([genome_id, seq_id, "Null", "Null"])
                seq_id = None
                genome_id = None
            if parsed_kmers % 2_000_000 == 0:
                logger.info(
                    f"Parsed {int(parsed_kmers/2)} prefix/suffix kmers!")
    return parsed_data


def write_to_tsv(data, output):
    with gzip.open(output, "wt") as o:
        o.write("genomeID\tkmerID\tContig\tLocation\n")
        for lines in data:
            o.write(f"{lines[0]}\t{lines[1]}\t{lines[2]}\t{lines[3]}\n")
    logger.info(f"Wrote output to {output}")


def main():
    parser = argparse.ArgumentParser(
        description="Read in raw fastmap output and parse it into a tsv file")

    parser.add_argument(
        "-i",
        "--input",
        type=str,
        required=True,
        help="Input bwa fastmap output",
        metavar="FILE",
    )

    parser.add_argument(
        "-o",
        "--output",
        type=str,
        required=True,
        help="Output analysis for bwa fastmap",
        metavar="FILE",
    )

    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help=
        "Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    # Parse the arguments
    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    data = parse_fastmap_output(args.input)
    logger.info(f"Writing {len(data)} fastmapped locations to {args.output}")
    Path(os.path.dirname(args.output)).mkdir(parents=True, exist_ok=True)
    write_to_tsv(data, args.output)


if __name__ == "__main__":
    main()
