#!/usr/bin/env python

import pandas as pd
import argparse
import glob
from loguru import logger
import sys
import os
import subprocess
import numpy as np
import concurrent.futures
from scipy.stats import chi2_contingency
from scipy.stats import fisher_exact
import statsmodels.api as sm
from statsmodels.stats.multitest import multipletests


def readin_and_add_columns(metadata, inputcsv, columns_to_add):
    df = pd.read_csv(inputcsv)
    sp_mapping = pd.read_csv(metadata, sep='\t')

    df_merged = pd.merge(df,
                         sp_mapping[columns_to_add + ['sample_id']],
                         left_on='GenomeID',
                         right_on='sample_id',
                         how='left')
    df_merged.drop('sample_id', axis=1, inplace=True)
    df = df_merged
    df['Cluster'] = df['Cluster'].astype(str)
    return df


def test_cluster_species_associations(df, cluster_col, species_col):
    contingency_table = pd.crosstab(df[cluster_col], df[species_col])
    print(contingency_table)
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    if p < 0.05:
        residuals = (contingency_table - expected) / np.sqrt(expected)
        # Identify significant cells
        print(expected)
        print(residuals)
        significant_cells = np.abs(residuals) > 2
        print(significant_cells)
        significant_pairs = contingency_table[significant_cells]


def test_species_proportion_in_cluster(df, cluster_col, species_col,
                                       overall_proportions):
    """
    Perform a z-test to check if the proportion of each species in each cluster
    is significantly different from its overall proportion in the dataset.
    Apply FDR correction for multiple hypothesis testing.

    Parameters:
    df (DataFrame): The dataset containing cluster and species information.
    cluster_col (str): The name of the column representing cluster assignments.
    species_col (str): The name of the column representing species.
    overall_proportions (dict): A dictionary with species as keys and their overall proportions as values.
    """
    p_values = []
    results = []

    # Iterate over each species
    for species_name, overall_proportion in overall_proportions.items():
        # Filter the dataframe for the specific species
        species_data = df[df[species_col] == species_name]

        # Count the occurrences of the species in each cluster
        cluster_counts = species_data[cluster_col].value_counts()

        # Perform the test for each cluster
        for cluster, count in cluster_counts.items():
            # Total number of observations in the cluster
            nobs = df[cluster_col].value_counts()[cluster]

            # Perform the z-test
            stat, pval = sm.stats.proportions_ztest(count, nobs,
                                                    overall_proportion)
            p_values.append(pval)
            results.append((species_name, cluster, stat, pval))

    # Apply FDR correction
    corrected_p_values = multipletests(p_values, alpha=0.05,
                                       method='fdr_bh')[1]

    # Log the results
    for (species_name, cluster, stat,
         original_pval), corrected_pval in zip(results, corrected_p_values):
        if corrected_pval < 0.05:
            logger.info(
                f"Significant proportion difference for {species_name} in Cluster {cluster}: z = {stat:.2f}, p = {corrected_pval:.3f}"
            )
        # else:
        # logger.info(f"No significant proportion difference for {species_name} in Cluster {cluster}: z = {stat:.2f}, p = {corrected_pval:.3f}")


def test_cluster_associations(df, columns_to_test):
    cluster_values = df['Cluster'].unique()

    for column in columns_to_test:
        logger.info(f"Testing associations in column: {column}")

        for cluster_value in cluster_values:
            for test_value in df[column].unique():
                # Filter for the specific cluster
                cluster_filtered = df[df['Cluster'] == cluster_value]

                # Count the number of occurrences of the test value
                test_value_count = (
                    cluster_filtered[column] == test_value).sum()
                total_count = len(cluster_filtered)

                # Perform binomial test
                p_value = binomtest(
                    test_value_count, total_count,
                    0.5).pvalue  # Assuming 50% probability by default

                # Check if the result is significant
                if p_value < 0.05:
                    logger.success(
                        f"Significant association found: Cluster '{cluster_value}' with '{test_value}' in '{column}' (P-value: {p_value})"
                    )


def main():
    parser = argparse.ArgumentParser(
        description=
        "Check if a given identified cluster segments along metadata")
    parser.add_argument(
        "-i",
        "--inputpassinggenecsv",
        type=str,
        required=True,
        help="Input CSV output for a passing gene",
    )
    parser.add_argument(
        "-m",
        "--inputmetadata",
        type=str,
        required=True,
        help="Input metadata file",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help=
        "Increase verbosity level. Can be specified multiple times for more detailed logs.",
    )

    args = parser.parse_args()

    if args.verbose == 0:
        logger.remove()
    elif args.verbose == 1:
        logger.remove()
        logger.add(sys.stderr, level="INFO")
    elif args.verbose >= 2:
        logger.remove()
        logger.add(sys.stderr, level="DEBUG")

    logger.info("Reading input cluster csv")

    columns = [
        'major_species', 'phylum', 'class', 'order', 'family', 'genus',
        'species'
    ]
    df = readin_and_add_columns(args.inputmetadata, args.inputpassinggenecsv,
                                columns)
    # for i in columns:
    # test_cluster_species_associations(df, 'Cluster', i)
    test_cluster_species_associations(df, 'Cluster', 'major_species')
    # column_picked = 'phylum'
    # overall_proportions = {s: df[df[column_picked] == s].shape[0] / df.shape[0] for s in df[column_picked].unique()}
    # test_species_proportion_in_cluster(df, 'Cluster', column_picked, overall_proportions)


if __name__ == "__main__":
    main()
